# Generated by Django 3.1.4 on 2021-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210309_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
