# Generated by Django 3.1.4 on 2021-05-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210425_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-id']},
        ),
    ]
